name: Check file size
on:
  push: # run the action on every push on any branch
  workflow_dispatch: # to run this workflow manually from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ppremk/lfs-warning@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Optional
          filesizelimit: 10MB # this is 10MB so we can sync to HF Spaces
